# Generated by Django 5.0.7 on 2024-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text_first', models.CharField(max_length=50)),
                ('about_text_second', models.CharField(max_length=50)),
                ('about_text_third', models.CharField(max_length=50)),
                ('about_our_mission', models.CharField(max_length=500)),
                ('about_what_we_do', models.CharField(max_length=500)),
                ('about_our_team', models.CharField(max_length=500)),
                ('about_why_choose_us', models.CharField(max_length=500)),
                ('about_contact_us', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_image', models.FileField(upload_to='client_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_mobile', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=250)),
                ('contact_message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=500)),
                ('faq_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(max_length=100)),
                ('portfolio_description', models.CharField(max_length=500)),
                ('prortfolio_link', models.CharField(max_length=500)),
                ('portfolio_image', models.FileField(upload_to='portfolio_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_name', models.CharField(max_length=100)),
                ('seeker_contact', models.CharField(max_length=20)),
                ('seeker_email', models.CharField(max_length=500)),
                ('seeker_job_post', models.CharField(max_length=500)),
                ('seeker_experience', models.IntegerField(default=0)),
                ('seeker_other_details', models.CharField(max_length=500)),
                ('seeker_resume', models.FileField(upload_to='resume_documents/')),
                ('seeker_submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_description', models.CharField(max_length=500)),
                ('slider_image', models.FileField(upload_to='slider_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_designation', models.CharField(max_length=500)),
                ('member_qualification', models.CharField(max_length=500)),
                ('member_image', models.FileField(upload_to='team_member_images/')),
                ('member_instagram', models.CharField(max_length=500)),
                ('member_facebook', models.CharField(max_length=500)),
                ('member_twitter', models.CharField(max_length=500)),
                ('member_linkedin', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=100)),
                ('testimonial_designation', models.CharField(max_length=500)),
                ('testimonial_description', models.CharField(max_length=500)),
                ('testimonial_image', models.FileField(upload_to='testimonial_images/')),
            ],
        ),
    ]
