# Generated by Django 5.0.7 on 2024-07-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananasitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_text_first', models.CharField(max_length=100)),
                ('contact_text_second', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_website_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutu',
            name='about_text_first',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutu',
            name='about_text_second',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutu',
            name='about_text_third',
            field=models.CharField(max_length=150),
        ),
    ]
